server: {host: "127.0.0.1", port: 3307}
backend: {type: "database", database: {type: "sqlite", url: ":memory:", max_connections: 1}}
tenants:
  - id: 1
    path: "/scim/v2"
    auth: {type: "unauthenticated"}
compatibility:
  meta_datetime_format: "rfc3339"
  show_empty_groups_members: true
  include_user_groups: true
  support_group_members_filter: true
  support_group_displayname_filter: true
  support_patch_replace_empty_array: false
  support_patch_replace_empty_value: false
